#!/bin/bash
if [ $1 ]
then
    log=$1
else
    log="qexe.log"
fi

if [ -e "$log" ];
then
    tail -n 30 $log
fi
njobs=$(( $(qstat | wc -l)-2 ))
(($njobs<0)) && njobs=0
echo Remaining jobs: $njobs
qstat

# watch watchlog
#'tail -n 30 qexe.log; echo Remaining jobs: `qstat | wc -l`; qstat;'
